name: Build your hugo website

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.0'

      - name: Build
        run: cd website && hugo --gc --minify --themesDir ../..

      - name: Deploy to live website
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
          #external_repository:  gurusabarish/hugo-profile-demo
          publish_branch: demo
          user_name: Github Actions deployment bot
          user_email: githubactionsbot@users.noreply.github.com
